import './globals.css'
import { Inter } from 'next/font/google'
import Image from "next/image";

const inter = Inter({ subsets: ['latin'] })

// These styles apply to every route in the application
import './globals.css'

export const metadata = {
  title: 'Baltic Studios',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="de">
      <body className={`bg-black text-white ${inter.className}`}>

      <header className="bg-transparent absolute top-0 left-0 w-full">
          <nav className="mx-auto flex xl:w-3/4 w-5/6 items-center justify-between py-6 z-99999" aria-label="Global">
              <div className="flex lg:flex-1">
                  <a href="#" className="-m-1.5 p-1.5">
                      <span className="sr-only">Lol</span>
                      <Image
                          src="/assets/logo.png"
                          alt="Vercel Logo"
                          width={200}
                          height={48}
                          priority
                      />
                  </a>
              </div>
              <div className="flex lg:hidden">
                  <button type="button"
                          className="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700">
                      <span className="sr-only">Open main menu</span>
                      <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor"
                           aria-hidden="true">
                          <path stroke-linecap="round" stroke-linejoin="round"
                                d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5"/>
                      </svg>
                  </button>
              </div>
              <div className="hidden lg:flex lg:gap-x-12">

              </div>
              <div className="hidden lg:flex lg:flex-1 lg:gap-x-12 mt-2 lg:justify-end">
                  <a href="/" className="text-white px-3 py-2 nav-link rounded-md text-sm font-medium">STARTSEITE</a>
                  <a href="about-us"
                     className="text-white px-3 py-2 nav-link text-[#ABABAB] rounded-md text-sm font-medium">TEAM</a>
                  <a href="apply"
                     className="text-white px-3 py-2 rounded-md bg-white/[.10] hover:border-white text-sm font-medium">🚀
                      Wir suchen dich!</a>

              </div>
          </nav>

      </header>

      {children}

      <div className=" p-10 xl:p-10 pb-12 mt-22 ">
          <div className="grid xl:grid-cols-3 grid-cols-2 xl:h-16 h-10 gap-x-4 xl:mx-24 border-gray-800 border-b">
              <div className="h-fit">
                  <Image
                      src="/assets/logo.png"
                      width={200}
                      height={200}
                      alt="Baltic Studios Logo"
                  />
              </div>
              <div className="h-fit w-full">
                  <p className="xl:text-xl mt-1 text-[12px] text-gray-500">Ein Universum voller Ideen</p>
              </div>
              <div className="h-fit">
              </div>

          </div>

          <div className="grid grid-cols-4 gap-x-4 xl:mx-24 justify-items-center pt-10 py-38">
              <div className="h-fit col-span-4 xl:col-span-1">
                  <h2 className="text-white">© BALTIC STUDIOS</h2>
                  <p className="text-gray-400 text-sm mt-3">Lorem ipsum dolor sit, sed sit amet, consetetur sadipscing
                      elitr, sed diam nonumy eirmod tempor.</p>
                  <p className="text-gray-400 text-sm mt-3">Dieses Projekt steht in keiner Verbindung mit Minecraft®, Disney® und
                      deren Marken</p>

              </div>
              <div className="h-fit mt-6 xl:mt-0 col-span-4 xl:col-span-2">
                  <ul className="grid grid-cols-2 gap-x-8 xl:gap-x-52 text-gray-500">
                      <li><a className="hover:text-gray-400 hover:cursor-pointer">Homepage</a></li>
                      <li><a className="hover:text-gray-400 hover:cursor-pointer">Über Uns</a></li>
                      <li><a className="hover:text-gray-400 hover:cursor-pointer">Bewerben</a></li>
                      <li><a className="hover:text-gray-400 hover:cursor-pointer">AGB</a></li>
                      <li><a className="hover:text-gray-400 hover:cursor-pointer">Datenschutzerklärung</a></li>
                      <li><a className="hover:text-gray-400 hover:cursor-pointer">Impressum</a></li>
                  </ul>
              </div>
              <div className="h-fit mt-5 text-white col-span-4 xl:col-span-1">

                  <a className="px-4 py-3 mt-5 xl:mt-0 rounded bg-white/[0.07] hover:bg-white/[0.1] hover:cursor-pointer">Baltic
                      Galaxy besuchen</a>
                  <div className="flex xl:justify-end px-4 bg-transparent text-white">
                      <div className="py-6 flex">
                          <div className="flex xl:flex items-center space-x-5">
                              <a className="flex hover:text-gray-200" href="#">
                                  <Image
                                      src="/assets/images/tiktok.svg"
                                      width={40}
                                      height={40}
                                      alt="Picture of the author"
                                  />
                              </a>
                              <a className="flex items-center hover:text-gray-200" href="#">
                                  <Image
                                      src="/assets/images/twitter.svg"
                                      width={40}
                                      height={40}
                                      alt="Picture of the author"
                                  />
                              </a>

                              <a className="flex items-center hover:text-gray-200" href="#">
                                  <Image
                                      src="/assets/images/youtube.svg"
                                      width={40}
                                      height={40}
                                      alt="Picture of the author"
                                  />
                              </a>

                          </div>
                      </div>
                  </div>
              </div>

          </div>

      </div>
      </body>
    </html>
  )
}
